M48
; DRILL file {KiCad 7.0.10} date Wed Jan 17 23:47:48 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-17T23:47:48+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.067
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X90.613Y-104.73
X91.629Y-99.65
X92.645Y-104.73
T2
X40.6Y-128.0
X50.6Y-60.6
X83.8Y-128.25
M30
